### ISSUE TITLE
bypass acceptance tests for release notes

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/haproxy-boshrelease#215]
- With the addition of acceptance tests, the build time got bumped significantly higher. (> 20m)
- Acceptance tests are expensive and only make sense if there are changes to test.
- To make a new release, we need to add release_notes.md
- CI should skip acceptance tests if the PR contains **only** release_notes.md (maybe also README.md changes)
- CI should still run tests if the PR contains other code

**Comment by peanball** [comment]
We could add `[no-ci]` or some similar text to release note commits, which would not run the CI task, or rather run an abbreviated task that skips CI and marks the step successful.

**Comment by plowin** [comment]
I think rel-notes are often part of a PR including a feature.
As label is on a PR, we probably rather need to adjust it on a code-level

**Comment by peanball** [comment]
Please consider any file changes that don't affect the acceptance tests as "to be ignored". This includes the pipeline definition and support scripts for the pipeline (e.g. `shipit`)
